Feature/exercicio002
rgbritoamanda/orionbootcamp pull request #2
Opened 2024-10-02 00:32 UTC by rgbritoamanda

**Este pull request inclui a resolução do exercício 002, com implementação de funcionalidades CRUD e opção de desfazer exclusões.**

**Resolução do Exercício 002:**

- Implementação de operações CRUD (Create, Read, Update, Delete) para gerenciar uma lista de cientistas famosos.
- Cada função foi implementada em dois paradigmas: imperativo e funcional.
- Adicionada a funcionalidade de desfazer exclusões, permitindo restaurar o último item deletado.
- Utilização da interface readline2 para interação com o usuário, oferecendo a possibilidade de realizar as operações diretamente via terminal.

**Funcionalidades implementadas:**

- Obter bio ou nome por ID: O usuário pode fornecer um ID para recuperar a biografia ou nome do cientista correspondente.
- Deletar por ID e Desfazer Exclusão: Deleção de cientistas pelo ID fornecido.
- Opção de desfazer a última exclusão realizada.
- Atualizar dados pelo ID: Atualização do nome e/ou bio de um cientista pelo ID fornecido.
- Listar IDs disponíveis: Ao realizar cada operação, o sistema informa os IDs disponíveis para facilitar a escolha do usuário.

**Como Rodar o Projeto:**

Certifique-se de ter o ts-node instalado: _npm install -g ts-node_
Navegue até a pasta "exercicios": _cd exercicios_
Execute o código: _ts-node ex002.ts_

2024-10-02 15:35 UTC, ErickBatista03 requested changes
Deixei um comentário de melhoria de uma das funções, de resto ta show. Tiver alguma dúvida só chamar

2024-10-02 15:35 UTC, ErickBatista03 commented on exercicios/ex002.ts
> +function updateByIdImperativo(id: number, newName?: string, newBio?: string): void {
Quando há vários parâmetros dessa forma é melhor colocar como um objeto, exemplo:

`function updateByIdImperativo(params: { id: number, newName?: string, newBio?: string })`
E você pode acessar eles facilmente usando params.id por exemplo ou desestruturando:
`const { id, newName, newBio } = params`.

Fazendo dessa forma resolve 2 problemas:
1 - Como newName e newBio são opcionais, caso queira alterar apenas a Bio é necessário passar undefined ou null em newName, não fica tão legal essa implementação. Na nova implementação não é necessário passar newName se não quiser.

2 - Melhora a legibilidade no uso da função:
`updateByIdImperativo(1, 'novo nome', 'nova bio')`
dessa forma você não tem certeza o que é 1, novo nome e nova bio.

Porém fazendo assim:
`updateByIdImperativo({ id: 1, name: 'novo nome', bio: 'nova bio' })`
Já vai ficar claro o que é cada parâmetro enviado

2024-10-02 15:35 UTC, ErickBatista03 commented on exercicios/ex002.ts
> +function updateByIdFuncional(id: number, newName?: string, newBio?: string): void {
Mesma coisa dos parâmetros que comentei acima

2024-10-04 17:10 UTC, robsonfgomes-newrizon approved these changes

2024-10-04 17:10 UTC, merged